# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Hatena
version:      0.13
version_from: lib/Text/Hatena.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0.04
    HTML::Parser:                  3.26
    LWP::UserAgent:                2
    Net::Amazon:                   0.34
    Template:                      2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
