# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Hatena
version:      0.06
version_from: lib/Text/Hatena.pm
installdirs:  site
requires:
    HTML::Parser:                  3.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
